version: "3.9"

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_assignment
    restart: unless-stopped
    tty: true
    ports:
      - "5454:5432"
    environment:
      POSTGRES_DB: lagalt
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: postgres:/data/postgres
    volumes:
      - postgres-data:/data/postgres

  pgadmin:
    container_name: pgadmin4_assignment
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/data/pgadmin
    ports:
      - "5050:80"

volumes:
  postgres-data:
  pgadmin: